export  {default as Dashboard } from "./Dashboard"
export  {default as Settings } from "./Settings"
export  {default as Tasks } from "./Tasks"
export  {default as Clients } from "./Clients"
export  {default as Projects} from "./Projects"